<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DriverSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('drivers')->insert([
            [
                "name" => "Hamilton",
                "surname" => "Lewis",
                "birth_date" => "1985-01-07",
                "nationality" => "British",
                "team" => "Mercedes",
                "win" => 103,
                "pole" => 104,
                "podium" => 197,
                "first_entry" => 2007,
                "driver_number" => 44,
                "fastest_laps" => 66,
                "career_points"=> 4681.5,
                "entries" => 340,
                "world_championship" => 7
            ],
            [
                "name"=> "Russell",
                "surname"=> "George",
                "birth_date"=> "1998-02-15",
                "nationality"=> "British",
                "team"=> "Mercedes",
                "win"=> 1,
                "pole"=> 1,
                "podium"=> 11,
                "first_entry"=> 2019,
                "driver_number"=> 63,
                "fastest_laps"=> 7,
                "career_points"=> 523,
                "entries"=> 112,
                "world_championship"=> 0
            ],
            [
                "name"=> "Verstappen",
                "surname"=>"Max",
                "birth_date"=> "1997-09-30",
                "nationality"=> "Dutch",
                "team"=> "Redbull",
                "win"=> 59,
                "pole"=> 39,
                "podium"=> 104,
                "first_entry"=>2015,
                "driver_number"=>1,
                "fastest_laps"=> 32,
                "career_points"=> 2755.5,
                "entries"=>193,
                "world_championship"=>3
            ],
            [
                "name"=> "Pérez",
                "surname"=> "Sergio",
                "birth_date"=> "1990-01-26",
                "nationality"=> "Mexican",
                "team"=> "Redbull",
                "win"=> 6,
                "pole"=>3,
                "podium"=> 39,
                "first_entry"=>2011,
                "driver_number"=> 11,
                "fastest_laps"=> 11,
                "career_points"=> 1593,
                "entries"=> 269,
                "world_championship"=> 0
            ],
            [
                "name"=> "Leclerc",
                "surname"=> "Charles",
                "birth_date"=> "1997-10-16",
                "nationality"=> "Monégasque",
                "team"=> "Ferrari",
                "win"=> 6,
                "pole"=>24,
                "podium"=> 35,
                "first_entry"=>2018,
                "driver_number"=> 16,
                "fastest_laps"=> 9,
                "career_points"=> 1212,
                "entries"=> 133,
                "world_championship"=> 0
            ],
            [
                "name"=> "Sainz",
                "surname"=> "Carlos",
                "birth_date"=> "1994-09-01",
                "nationality"=> "Spanish",
                "team"=> "Ferrari",
                "win"=> 3,
                "pole"=> 5,
                "podium"=> 22,
                "first_entry"=> 2015,
                "driver_number"=> 55,
                "fastest_laps"=> 3,
                "career_points"=> 1090.5,
                "entries"=>193,
                "world_championship"=>0
            ],
            [
                "name"=> "Bearman",
                "surname"=> "Oliver",
                "birth_date"=> "2005-05-08",
                "nationality"=> "British",
                "team"=> "Ferrari",
                "win"=> 0,
                "pole"=> 0,
                "podium"=> 0,
                "first_entry"=> 2024,
                "driver_number"=> 38,
                "fastest_laps"=> 0,
                "career_points"=> 6,
                "entries"=>1,
                "world_championship"=>0
            ],
            [
                "name"=> "Norris",
                "surname"=> "Lando",
                "birth_date"=> "1999-11-13",
                "nationality"=> "British",
                "team"=> "McLaren",
                "win"=> 1,
                "pole"=> 1,
                "podium"=> 17,
                "first_entry"=>2019,
                "driver_number"=>4,
                "fastest_laps"=> 6,
                "career_points"=> 746,
                "entries"=> 112,
                "world_championship"=> 0
            ],
            [
                "name"=> "Piastri",
                "surname"=> "Oscar",
                "birth_date"=> "2001-04-06",
                "nationality"=> "Australian",
                "team"=> "McLaren",
                "win"=> 0,
                "pole"=> 0,
                "podium"=> 3,
                "first_entry"=> 2023,
                "driver_number"=> 81,
                "fastest_laps"=> 3,
                "career_points"=> 168,
                "entries"=> 30,
                "world_championship"=>0
            ],
            [
                "name"=> "Tsunoda" ,
                "surname"=> "Yuki",
                "birth_date"=> "2000-05-11",
                "nationality"=> "Japanese",
                "team"=> "Racing Bulls",
                "win"=> 0,
                "pole"=> 0,
                "podium"=> 0,
                "first_entry"=> 2021,
                "driver_number"=> 22,
                "fastest_laps"=> 1,
                "career_points"=> 80,
                "entries"=> 74,
                "world_championship"=>0
            ],
            [
                "name"=> "Ricciardo",
                "surname"=> "Daniel",
                "birth_date"=> "1989-07-01",
                "nationality"=> "Australian",
                "team"=> "Racing Bulls",
                "win"=> 8,
                "pole"=> 3,
                "podium"=> 32,
                "first_entry"=> 2011,
                "driver_number"=> 3,
                "fastest_laps"=> 16,
                "career_points"=> 1322,
                "entries"=>248,
                "world_championship"=>0
            ],
            [
                "name"=> "Alonso",
                "surname"=> "Fernando",
                "birth_date"=> "1981-07-29",
                "nationality"=> "Spanish",
                "team"=> "Aston Martin",
                "win"=> 32,
                "pole"=> 22,
                "podium"=> 106,
                "first_entry"=> 2001,
                "driver_number"=> 14,
                "fastest_laps"=> 25,
                "career_points"=> 2300,
                "entries"=>388,
                "world_championship"=>2
            ],
            [
                "name"=> "Stroll",
                "surname"=> "Lance",
                "birth_date"=> "1998-10-29",
                "nationality"=> "Canadian",
                "team"=> "Aston Martin",
                "win"=> 0,
                "pole"=> 1,
                "podium"=> 3,
                "first_entry"=> 2017,
                "driver_number"=> 18,
                "fastest_laps"=> 0,
                "career_points"=> 279,
                "entries"=>153,
                "world_championship"=>0
            ],
            [
                "name"=> "Hulkenberg",
                "surname"=> "Nico",
                "birth_date"=> "1987-08-19",
                "nationality"=> "German",
                "team"=> "Haas",
                "win"=> 0,
                "pole"=> 1,
                "podium"=> 0,
                "first_entry"=> 2010,
                "driver_number"=> 27,
                "fastest_laps"=> 2,
                "career_points"=> 536,
                "entries"=>248,
                "world_championship"=>0
            ],
            [
                "name"=> "Magnussen",
                "surname"=> "Kevin",
                "birth_date"=> "1992-10-05",
                "nationality"=> "Danish",
                "team"=> "Haas",
                "win"=> 0,
                "pole"=> 1,
                "podium"=> 1,
                "first_entry"=> 2014,
                "driver_number"=> 20,
                "fastest_laps"=> 2,
                "career_points"=> 187,
                "entries"=>172,
                "world_championship"=>0
            ],
            [
                "name"=> "Albon",
                "surname"=> "Alexander",
                "birth_date"=> "1996-03-23",
                "nationality"=> "Thai",
                "team"=> "Williams",
                "win"=> 0,
                "pole"=> 0,
                "podium"=> 2,
                "first_entry"=> 2019,
                "driver_number"=> 23,
                "fastest_laps"=> 0,
                "career_points"=> 230,
                "entries"=>90,
                "world_championship"=>0
            ],
            [
                "name"=> "Sargeant",
                "surname"=> "Logan",
                "birth_date"=> "2000-12-31",
                "nationality"=> "American",
                "team"=> "Williams",
                "win"=> 0,
                "pole"=> 0,
                "podium"=> 0,
                "first_entry"=> 2023,
                "driver_number"=> 2,
                "fastest_laps"=> 0,
                "career_points"=> 1,
                "entries"=>30,
                "world_championship"=>0
            ],
            [
                "name"=> "Ocon",
                "surname"=> "Esteban",
                "birth_date"=> "1996-09-17",
                "nationality"=> "French",
                "team"=> "Alpine",
                "win"=> 1,
                "pole"=> 0,
                "podium"=> 3,
                "first_entry"=> 2016,
                "driver_number"=> 31,
                "fastest_laps"=> 0,
                "career_points"=> 423,
                "entries"=>141,
                "world_championship"=>0
            ],
            [
                "name"=> "Gasly",
                "surname"=> "Pierre",
                "birth_date"=> "1996-02-07",
                "nationality"=> "French",
                "team"=> "Alpine",
                "win"=> 1,
                "pole"=> 0,
                "podium"=> 4,
                "first_entry"=> 2017,
                "driver_number"=> 10,
                "fastest_laps"=> 3,
                "career_points"=> 395,
                "entries"=>138,
                "world_championship"=>0
            ],
            [
                "name"=> "Bottas",
                "surname"=> "Valtteri",
                "birth_date"=> "1989-08-28",
                "nationality"=> "Finnish",
                "team"=> "Stake F1 Team Kick Sauber",
                "win"=> 10,
                "pole"=> 20,
                "podium"=> 67,
                "first_entry"=> 2013,
                "driver_number"=> 77,
                "fastest_laps"=> 19,
                "career_points"=> 1797,
                "entries"=>231,
                "world_championship"=>0
            ],
            [
                "name"=> "Zhou",
                "surname"=> "Guanyu",
                "birth_date"=> "1999-05-30",
                "nationality"=> "Chinese",
                "team"=> "Stake F1 Team Kick Sauber",
                "win"=> 0,
                "pole"=> 0,
                "podium"=> 0,
                "first_entry"=> 2022,
                "driver_number"=> 24,
                "fastest_laps"=> 2,
                "career_points"=> 12,
                "entries"=>52,
                "world_championship"=>0
            ]
        ]);
    }
}
